### ISSUE TITLE
Intermediate CA build issues

### ISSUE THREAD

**Issue by itsrickos** [ryankurte/pki#6]
When building the Intermediate CA with the build-int.sh there are a couple of errors. 

1. Your instructions  indicate passing in 3 variables but the code on build-int.sh (line 9) only expects 2
                 if [ "$#" -ne 2 ]; then 
this obviously generates an error and the code quits

2. If i omit the key name and just pass the intermediate CA cert name i get as far as 
      yk_sign_ca $DIR/yk-ca.crt $DIR/$FILE.csr $DIR/$FILE.conf $DIR/$FILE.crt 
      cat $DIR/roots.crt $DIR/$FILE.crt > $DIR/$FILE-chain.crt
before receiving these errors ........
PKCS11 library:PKCS11_rsa_sign:User not logged in:p11_ops.c:131:
asn1 encoding routines:ASN1_item_sign_ctx:EVP lib:a_sign.c:306:

**Comment by ryankurte** [comment]
Yeah you're correct, instructions need updating, you only need the [mode and name for the intermediate cert](https://github.com/ryankurte/pki/blob/0b11a04d4ec6f3266844c04460aee9dc47c8fc0e/build-int.sh#L10).

Hmm, I wonder whether that second part is related to [yubico-piv-tool#150](https://github.com/Yubico/yubico-piv-tool/issues/150).

**Comment by ryankurte** [comment]
thanks for the report! closed by re-write in #8
